/*flexberryautogenerated="true"*/
namespace IIS.VUZ
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class TeacherL : BaseListForm<Teacher>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public TeacherL() : base(Teacher.Views.TeacherL)
        {
            EditPage = TeacherE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Teacher/TeacherL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
