//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.VUZ
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Control form.
    /// </summary>
    // *** Start programmer edit section *** (ControlForm CustomAttributes)

    // *** End programmer edit section *** (ControlForm CustomAttributes)
    public enum ControlForm
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (ControlForm.Exam CustomAttributes)

        // *** End programmer edit section *** (ControlForm.Exam CustomAttributes)
        Exam,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (ControlForm.Credit CustomAttributes)

        // *** End programmer edit section *** (ControlForm.Credit CustomAttributes)
        Credit,
    }
}
