//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.VUZ
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Faculty.
    /// </summary>
    // *** Start programmer edit section *** (Faculty CustomAttributes)

    // *** End programmer edit section *** (Faculty CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("FacultyE", new string[] {
            "Name as \'Name\'"})]
    [View("FacultyL", new string[] {
            "Name as \'Name\'"})]
    public class Faculty : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        // *** Start programmer edit section *** (Faculty CustomMembers)

        // *** End programmer edit section *** (Faculty CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Faculty.Name CustomAttributes)

        // *** End programmer edit section *** (Faculty.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Faculty.Name Get start)

                // *** End programmer edit section *** (Faculty.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Faculty.Name Get end)

                // *** End programmer edit section *** (Faculty.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Faculty.Name Set start)

                // *** End programmer edit section *** (Faculty.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Faculty.Name Set end)

                // *** End programmer edit section *** (Faculty.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "FacultyE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FacultyE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FacultyE", typeof(IIS.VUZ.Faculty));
                }
            }
            
            /// <summary>
            /// "FacultyL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FacultyL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FacultyL", typeof(IIS.VUZ.Faculty));
                }
            }
        }
    }
}
