//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.VUZ
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Mark.
    /// </summary>
    // *** Start programmer edit section *** (Mark CustomAttributes)

    // *** End programmer edit section *** (Mark CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("MarkE", new string[] {
            "Value as \'Value\'",
            "Student as \'Student\'",
            "Student.GradeBookNumber as \'Grade book number\'",
            "Subject as \'Subject\'",
            "Subject.Name as \'Name\'",
            "Teacher as \'Teacher\'",
            "Teacher.Fullname as \'Fullname\'"})]
    [View("MarkL", new string[] {
            "Value as \'Value\'",
            "Student.GradeBookNumber as \'Grade book number\'",
            "Subject.Name as \'Name\'",
            "Teacher.Fullname as \'Fullname\'"})]
    public class Mark : ICSSoft.STORMNET.DataObject
    {
        
        private int fValue;
        
        private IIS.VUZ.Student fStudent;
        
        private IIS.VUZ.Subject fSubject;
        
        private IIS.VUZ.Teacher fTeacher;
        
        // *** Start programmer edit section *** (Mark CustomMembers)

        // *** End programmer edit section *** (Mark CustomMembers)

        
        /// <summary>
        /// Value.
        /// </summary>
        // *** Start programmer edit section *** (Mark.Value CustomAttributes)

        // *** End programmer edit section *** (Mark.Value CustomAttributes)
        public virtual int Value
        {
            get
            {
                // *** Start programmer edit section *** (Mark.Value Get start)

                // *** End programmer edit section *** (Mark.Value Get start)
                int result = this.fValue;
                // *** Start programmer edit section *** (Mark.Value Get end)

                // *** End programmer edit section *** (Mark.Value Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Mark.Value Set start)

                // *** End programmer edit section *** (Mark.Value Set start)
                this.fValue = value;
                // *** Start programmer edit section *** (Mark.Value Set end)

                // *** End programmer edit section *** (Mark.Value Set end)
            }
        }
        
        /// <summary>
        /// Mark.
        /// </summary>
        // *** Start programmer edit section *** (Mark.Student CustomAttributes)

        // *** End programmer edit section *** (Mark.Student CustomAttributes)
        [PropertyStorage(new string[] {
                "Student"})]
        [NotNull()]
        public virtual IIS.VUZ.Student Student
        {
            get
            {
                // *** Start programmer edit section *** (Mark.Student Get start)

                // *** End programmer edit section *** (Mark.Student Get start)
                IIS.VUZ.Student result = this.fStudent;
                // *** Start programmer edit section *** (Mark.Student Get end)

                // *** End programmer edit section *** (Mark.Student Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Mark.Student Set start)

                // *** End programmer edit section *** (Mark.Student Set start)
                this.fStudent = value;
                // *** Start programmer edit section *** (Mark.Student Set end)

                // *** End programmer edit section *** (Mark.Student Set end)
            }
        }
        
        /// <summary>
        /// Mark.
        /// </summary>
        // *** Start programmer edit section *** (Mark.Subject CustomAttributes)

        // *** End programmer edit section *** (Mark.Subject CustomAttributes)
        [PropertyStorage(new string[] {
                "Subject"})]
        [NotNull()]
        public virtual IIS.VUZ.Subject Subject
        {
            get
            {
                // *** Start programmer edit section *** (Mark.Subject Get start)

                // *** End programmer edit section *** (Mark.Subject Get start)
                IIS.VUZ.Subject result = this.fSubject;
                // *** Start programmer edit section *** (Mark.Subject Get end)

                // *** End programmer edit section *** (Mark.Subject Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Mark.Subject Set start)

                // *** End programmer edit section *** (Mark.Subject Set start)
                this.fSubject = value;
                // *** Start programmer edit section *** (Mark.Subject Set end)

                // *** End programmer edit section *** (Mark.Subject Set end)
            }
        }
        
        /// <summary>
        /// Mark.
        /// </summary>
        // *** Start programmer edit section *** (Mark.Teacher CustomAttributes)

        // *** End programmer edit section *** (Mark.Teacher CustomAttributes)
        [PropertyStorage(new string[] {
                "Teacher"})]
        [NotNull()]
        public virtual IIS.VUZ.Teacher Teacher
        {
            get
            {
                // *** Start programmer edit section *** (Mark.Teacher Get start)

                // *** End programmer edit section *** (Mark.Teacher Get start)
                IIS.VUZ.Teacher result = this.fTeacher;
                // *** Start programmer edit section *** (Mark.Teacher Get end)

                // *** End programmer edit section *** (Mark.Teacher Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Mark.Teacher Set start)

                // *** End programmer edit section *** (Mark.Teacher Set start)
                this.fTeacher = value;
                // *** Start programmer edit section *** (Mark.Teacher Set end)

                // *** End programmer edit section *** (Mark.Teacher Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "MarkE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MarkE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MarkE", typeof(IIS.VUZ.Mark));
                }
            }
            
            /// <summary>
            /// "MarkL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View MarkL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("MarkL", typeof(IIS.VUZ.Mark));
                }
            }
        }
    }
}
