//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.VUZ
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Person.
    /// </summary>
    // *** Start programmer edit section *** (Person CustomAttributes)

    // *** End programmer edit section *** (Person CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("PersonE", new string[] {
            "Fullname as \'Fullname\'",
            "BirthDate as \'Birth date\'"})]
    [View("PersonL", new string[] {
            "Fullname as \'Fullname\'",
            "BirthDate as \'Birth date\'"})]
    public class Person : ICSSoft.STORMNET.DataObject
    {
        
        private string fFullname;
        
        private System.DateTime fBirthDate = System.DateTime.Now;
        
        // *** Start programmer edit section *** (Person CustomMembers)

        // *** End programmer edit section *** (Person CustomMembers)

        
        /// <summary>
        /// Fullname.
        /// </summary>
        // *** Start programmer edit section *** (Person.Fullname CustomAttributes)

        // *** End programmer edit section *** (Person.Fullname CustomAttributes)
        [StrLen(255)]
        public virtual string Fullname
        {
            get
            {
                // *** Start programmer edit section *** (Person.Fullname Get start)

                // *** End programmer edit section *** (Person.Fullname Get start)
                string result = this.fFullname;
                // *** Start programmer edit section *** (Person.Fullname Get end)

                // *** End programmer edit section *** (Person.Fullname Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Person.Fullname Set start)

                // *** End programmer edit section *** (Person.Fullname Set start)
                this.fFullname = value;
                // *** Start programmer edit section *** (Person.Fullname Set end)

                // *** End programmer edit section *** (Person.Fullname Set end)
            }
        }
        
        /// <summary>
        /// BirthDate.
        /// </summary>
        // *** Start programmer edit section *** (Person.BirthDate CustomAttributes)

        // *** End programmer edit section *** (Person.BirthDate CustomAttributes)
        public virtual System.DateTime BirthDate
        {
            get
            {
                // *** Start programmer edit section *** (Person.BirthDate Get start)

                // *** End programmer edit section *** (Person.BirthDate Get start)
                System.DateTime result = this.fBirthDate;
                // *** Start programmer edit section *** (Person.BirthDate Get end)

                // *** End programmer edit section *** (Person.BirthDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Person.BirthDate Set start)

                // *** End programmer edit section *** (Person.BirthDate Set start)
                this.fBirthDate = value;
                // *** Start programmer edit section *** (Person.BirthDate Set end)

                // *** End programmer edit section *** (Person.BirthDate Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "PersonE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PersonE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PersonE", typeof(IIS.VUZ.Person));
                }
            }
            
            /// <summary>
            /// "PersonL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View PersonL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("PersonL", typeof(IIS.VUZ.Person));
                }
            }
        }
    }
}
