//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.VUZ
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Student.
    /// </summary>
    // *** Start programmer edit section *** (Student CustomAttributes)

    // *** End programmer edit section *** (Student CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("StudentE", new string[] {
            "GradeBookNumber as \'Grade book number\'",
            "Fullname as \'Fullname\'",
            "BirthDate as \'Birth date\'",
            "Group as \'Group\'",
            "Group.Number as \'Number\'"})]
    [View("StudentL", new string[] {
            "GradeBookNumber as \'Grade book number\'",
            "Fullname as \'Fullname\'",
            "BirthDate as \'Birth date\'",
            "Group.Number as \'Number\'"})]
    public class Student : IIS.VUZ.Person
    {
        
        private string fGradeBookNumber;
        
        private IIS.VUZ.Group fGroup;
        
        // *** Start programmer edit section *** (Student CustomMembers)

        // *** End programmer edit section *** (Student CustomMembers)

        
        /// <summary>
        /// GradeBookNumber.
        /// </summary>
        // *** Start programmer edit section *** (Student.GradeBookNumber CustomAttributes)

        // *** End programmer edit section *** (Student.GradeBookNumber CustomAttributes)
        [StrLen(255)]
        public virtual string GradeBookNumber
        {
            get
            {
                // *** Start programmer edit section *** (Student.GradeBookNumber Get start)

                // *** End programmer edit section *** (Student.GradeBookNumber Get start)
                string result = this.fGradeBookNumber;
                // *** Start programmer edit section *** (Student.GradeBookNumber Get end)

                // *** End programmer edit section *** (Student.GradeBookNumber Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Student.GradeBookNumber Set start)

                // *** End programmer edit section *** (Student.GradeBookNumber Set start)
                this.fGradeBookNumber = value;
                // *** Start programmer edit section *** (Student.GradeBookNumber Set end)

                // *** End programmer edit section *** (Student.GradeBookNumber Set end)
            }
        }
        
        /// <summary>
        /// Student.
        /// </summary>
        // *** Start programmer edit section *** (Student.Group CustomAttributes)

        // *** End programmer edit section *** (Student.Group CustomAttributes)
        [PropertyStorage(new string[] {
                "Group"})]
        [NotNull()]
        public virtual IIS.VUZ.Group Group
        {
            get
            {
                // *** Start programmer edit section *** (Student.Group Get start)

                // *** End programmer edit section *** (Student.Group Get start)
                IIS.VUZ.Group result = this.fGroup;
                // *** Start programmer edit section *** (Student.Group Get end)

                // *** End programmer edit section *** (Student.Group Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Student.Group Set start)

                // *** End programmer edit section *** (Student.Group Set start)
                this.fGroup = value;
                // *** Start programmer edit section *** (Student.Group Set end)

                // *** End programmer edit section *** (Student.Group Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "StudentE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View StudentE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("StudentE", typeof(IIS.VUZ.Student));
                }
            }
            
            /// <summary>
            /// "StudentL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View StudentL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("StudentL", typeof(IIS.VUZ.Student));
                }
            }
        }
    }
}
