//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.VUZ
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Subject.
    /// </summary>
    // *** Start programmer edit section *** (Subject CustomAttributes)

    // *** End programmer edit section *** (Subject CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SubjectE", new string[] {
            "Name as \'Name\'",
            "Control as \'Control\'",
            "BeginDate as \'Begin date\'",
            "EndDate as \'End date\'"})]
    [View("SubjectL", new string[] {
            "Name as \'Name\'",
            "Control as \'Control\'",
            "BeginDate as \'Begin date\'",
            "EndDate as \'End date\'"})]
    public class Subject : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private IIS.VUZ.ControlForm fControl;
        
        private System.DateTime fBeginDate;
        
        private System.DateTime fEndDate;
        
        // *** Start programmer edit section *** (Subject CustomMembers)

        // *** End programmer edit section *** (Subject CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Subject.Name CustomAttributes)

        // *** End programmer edit section *** (Subject.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Subject.Name Get start)

                // *** End programmer edit section *** (Subject.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Subject.Name Get end)

                // *** End programmer edit section *** (Subject.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Subject.Name Set start)

                // *** End programmer edit section *** (Subject.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Subject.Name Set end)

                // *** End programmer edit section *** (Subject.Name Set end)
            }
        }
        
        /// <summary>
        /// Control.
        /// </summary>
        // *** Start programmer edit section *** (Subject.Control CustomAttributes)

        // *** End programmer edit section *** (Subject.Control CustomAttributes)
        public virtual IIS.VUZ.ControlForm Control
        {
            get
            {
                // *** Start programmer edit section *** (Subject.Control Get start)

                // *** End programmer edit section *** (Subject.Control Get start)
                IIS.VUZ.ControlForm result = this.fControl;
                // *** Start programmer edit section *** (Subject.Control Get end)

                // *** End programmer edit section *** (Subject.Control Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Subject.Control Set start)

                // *** End programmer edit section *** (Subject.Control Set start)
                this.fControl = value;
                // *** Start programmer edit section *** (Subject.Control Set end)

                // *** End programmer edit section *** (Subject.Control Set end)
            }
        }
        
        /// <summary>
        /// BeginDate.
        /// </summary>
        // *** Start programmer edit section *** (Subject.BeginDate CustomAttributes)

        // *** End programmer edit section *** (Subject.BeginDate CustomAttributes)
        public virtual System.DateTime BeginDate
        {
            get
            {
                // *** Start programmer edit section *** (Subject.BeginDate Get start)

                // *** End programmer edit section *** (Subject.BeginDate Get start)
                System.DateTime result = this.fBeginDate;
                // *** Start programmer edit section *** (Subject.BeginDate Get end)

                // *** End programmer edit section *** (Subject.BeginDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Subject.BeginDate Set start)

                // *** End programmer edit section *** (Subject.BeginDate Set start)
                this.fBeginDate = value;
                // *** Start programmer edit section *** (Subject.BeginDate Set end)

                // *** End programmer edit section *** (Subject.BeginDate Set end)
            }
        }
        
        /// <summary>
        /// EndDate.
        /// </summary>
        // *** Start programmer edit section *** (Subject.EndDate CustomAttributes)

        // *** End programmer edit section *** (Subject.EndDate CustomAttributes)
        public virtual System.DateTime EndDate
        {
            get
            {
                // *** Start programmer edit section *** (Subject.EndDate Get start)

                // *** End programmer edit section *** (Subject.EndDate Get start)
                System.DateTime result = this.fEndDate;
                // *** Start programmer edit section *** (Subject.EndDate Get end)

                // *** End programmer edit section *** (Subject.EndDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Subject.EndDate Set start)

                // *** End programmer edit section *** (Subject.EndDate Set start)
                this.fEndDate = value;
                // *** Start programmer edit section *** (Subject.EndDate Set end)

                // *** End programmer edit section *** (Subject.EndDate Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SubjectE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SubjectE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SubjectE", typeof(IIS.VUZ.Subject));
                }
            }
            
            /// <summary>
            /// "SubjectL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SubjectL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SubjectL", typeof(IIS.VUZ.Subject));
                }
            }
        }
    }
}
