//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.VUZ
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Teacher.
    /// </summary>
    // *** Start programmer edit section *** (Teacher CustomAttributes)

    // *** End programmer edit section *** (Teacher CustomAttributes)
    [AutoAltered()]
    [ICSSoft.STORMNET.NotStored(false)]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("TeacherE", new string[] {
            "Title as \'Title\'",
            "Fullname as \'Fullname\'",
            "BirthDate as \'Birth date\'"})]
    [View("TeacherL", new string[] {
            "Title as \'Title\'",
            "Fullname as \'Fullname\'",
            "BirthDate as \'Birth date\'"})]
    public class Teacher : IIS.VUZ.Person
    {
        
        private IIS.VUZ.TitleType fTitle;
        
        // *** Start programmer edit section *** (Teacher CustomMembers)

        // *** End programmer edit section *** (Teacher CustomMembers)

        
        /// <summary>
        /// Title.
        /// </summary>
        // *** Start programmer edit section *** (Teacher.Title CustomAttributes)

        // *** End programmer edit section *** (Teacher.Title CustomAttributes)
        public virtual IIS.VUZ.TitleType Title
        {
            get
            {
                // *** Start programmer edit section *** (Teacher.Title Get start)

                // *** End programmer edit section *** (Teacher.Title Get start)
                IIS.VUZ.TitleType result = this.fTitle;
                // *** Start programmer edit section *** (Teacher.Title Get end)

                // *** End programmer edit section *** (Teacher.Title Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Teacher.Title Set start)

                // *** End programmer edit section *** (Teacher.Title Set start)
                this.fTitle = value;
                // *** Start programmer edit section *** (Teacher.Title Set end)

                // *** End programmer edit section *** (Teacher.Title Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "TeacherE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TeacherE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TeacherE", typeof(IIS.VUZ.Teacher));
                }
            }
            
            /// <summary>
            /// "TeacherL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TeacherL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TeacherL", typeof(IIS.VUZ.Teacher));
                }
            }
        }
    }
}
