//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.VUZ
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Theme.
    /// </summary>
    // *** Start programmer edit section *** (Theme CustomAttributes)

    // *** End programmer edit section *** (Theme CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ThemeE", new string[] {
            "Name as \'Name\'",
            "Description as \'Description\'",
            "BeginDate as \'Begin date\'",
            "EndDate as \'End date\'",
            "Subject as \'Subject\'",
            "Subject.Name as \'Name\'"})]
    [View("ThemeL", new string[] {
            "Name as \'Name\'",
            "Description as \'Description\'",
            "BeginDate as \'Begin date\'",
            "EndDate as \'End date\'",
            "Subject.Name as \'Name\'"})]
    public class Theme : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private string fDescription;
        
        private System.DateTime fBeginDate;
        
        private System.DateTime fEndDate;
        
        private IIS.VUZ.Subject fSubject;
        
        // *** Start programmer edit section *** (Theme CustomMembers)

        // *** End programmer edit section *** (Theme CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Theme.Name CustomAttributes)

        // *** End programmer edit section *** (Theme.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Theme.Name Get start)

                // *** End programmer edit section *** (Theme.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Theme.Name Get end)

                // *** End programmer edit section *** (Theme.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Theme.Name Set start)

                // *** End programmer edit section *** (Theme.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Theme.Name Set end)

                // *** End programmer edit section *** (Theme.Name Set end)
            }
        }
        
        /// <summary>
        /// Description.
        /// </summary>
        // *** Start programmer edit section *** (Theme.Description CustomAttributes)

        // *** End programmer edit section *** (Theme.Description CustomAttributes)
        [StrLen(255)]
        public virtual string Description
        {
            get
            {
                // *** Start programmer edit section *** (Theme.Description Get start)

                // *** End programmer edit section *** (Theme.Description Get start)
                string result = this.fDescription;
                // *** Start programmer edit section *** (Theme.Description Get end)

                // *** End programmer edit section *** (Theme.Description Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Theme.Description Set start)

                // *** End programmer edit section *** (Theme.Description Set start)
                this.fDescription = value;
                // *** Start programmer edit section *** (Theme.Description Set end)

                // *** End programmer edit section *** (Theme.Description Set end)
            }
        }
        
        /// <summary>
        /// BeginDate.
        /// </summary>
        // *** Start programmer edit section *** (Theme.BeginDate CustomAttributes)

        // *** End programmer edit section *** (Theme.BeginDate CustomAttributes)
        public virtual System.DateTime BeginDate
        {
            get
            {
                // *** Start programmer edit section *** (Theme.BeginDate Get start)

                // *** End programmer edit section *** (Theme.BeginDate Get start)
                System.DateTime result = this.fBeginDate;
                // *** Start programmer edit section *** (Theme.BeginDate Get end)

                // *** End programmer edit section *** (Theme.BeginDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Theme.BeginDate Set start)

                // *** End programmer edit section *** (Theme.BeginDate Set start)
                this.fBeginDate = value;
                // *** Start programmer edit section *** (Theme.BeginDate Set end)

                // *** End programmer edit section *** (Theme.BeginDate Set end)
            }
        }
        
        /// <summary>
        /// EndDate.
        /// </summary>
        // *** Start programmer edit section *** (Theme.EndDate CustomAttributes)

        // *** End programmer edit section *** (Theme.EndDate CustomAttributes)
        public virtual System.DateTime EndDate
        {
            get
            {
                // *** Start programmer edit section *** (Theme.EndDate Get start)

                // *** End programmer edit section *** (Theme.EndDate Get start)
                System.DateTime result = this.fEndDate;
                // *** Start programmer edit section *** (Theme.EndDate Get end)

                // *** End programmer edit section *** (Theme.EndDate Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Theme.EndDate Set start)

                // *** End programmer edit section *** (Theme.EndDate Set start)
                this.fEndDate = value;
                // *** Start programmer edit section *** (Theme.EndDate Set end)

                // *** End programmer edit section *** (Theme.EndDate Set end)
            }
        }
        
        /// <summary>
        /// Theme.
        /// </summary>
        // *** Start programmer edit section *** (Theme.Subject CustomAttributes)

        // *** End programmer edit section *** (Theme.Subject CustomAttributes)
        [PropertyStorage(new string[] {
                "Subject"})]
        [NotNull()]
        public virtual IIS.VUZ.Subject Subject
        {
            get
            {
                // *** Start programmer edit section *** (Theme.Subject Get start)

                // *** End programmer edit section *** (Theme.Subject Get start)
                IIS.VUZ.Subject result = this.fSubject;
                // *** Start programmer edit section *** (Theme.Subject Get end)

                // *** End programmer edit section *** (Theme.Subject Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Theme.Subject Set start)

                // *** End programmer edit section *** (Theme.Subject Set start)
                this.fSubject = value;
                // *** Start programmer edit section *** (Theme.Subject Set end)

                // *** End programmer edit section *** (Theme.Subject Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ThemeE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ThemeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ThemeE", typeof(IIS.VUZ.Theme));
                }
            }
            
            /// <summary>
            /// "ThemeL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ThemeL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ThemeL", typeof(IIS.VUZ.Theme));
                }
            }
        }
    }
}
