//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.VUZ
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Title type.
    /// </summary>
    // *** Start programmer edit section *** (TitleType CustomAttributes)

    // *** End programmer edit section *** (TitleType CustomAttributes)
    public enum TitleType
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TitleType.СтаршийПреподаватель CustomAttributes)

        // *** End programmer edit section *** (TitleType.СтаршийПреподаватель CustomAttributes)
        СтаршийПреподаватель,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TitleType.Доцент CustomAttributes)

        // *** End programmer edit section *** (TitleType.Доцент CustomAttributes)
        Доцент,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (TitleType.Профессор CustomAttributes)

        // *** End programmer edit section *** (TitleType.Профессор CustomAttributes)
        Профессор,
    }
}
