/*flexberryautogenerated="true"*/
namespace IIS.VUZ
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class ThemeL : BaseListForm<Theme>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public ThemeL() : base(IIS.VUZ.Theme.Views.ThemeL)
        {
            EditPage = ThemeE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Theme/ThemeL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
