/*flexberryautogenerated="true"*/
namespace IIS.VUZ
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class StudentL : BaseListForm<Student>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public StudentL() : base(Student.Views.StudentL)
        {
            EditPage = StudentE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Student/StudentL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
